#!/bin/sh
#
# The purpose of this script is to find all backups associated 
# with my instance-ID with the intent of expiring any images that
# are older than the threshold date. The script will pull the the
# instance-ID from the instance meta-data URL, then search for
# Snapshots that were previously generated by the backup scripts
# found elsewhere in this tool-set.
#
# Dependencies:
# - Generic: See the top-level README_dependencies.md for script dependencies
#
# License:
# - This script released under the Apache 2.0 OSS License
#
######################################################################
WHEREAMI=`readlink -f ${0}`
SCRIPTDIR=`dirname ${WHEREAMI}`
TARGVG=${1:-UNDEF}

# Put the bulk of our variables into an external file so they
# can be easily re-used across scripts
source ${SCRIPTDIR}/commonVars.env

# Grab a filtered list candidate snapshots and dump to an array
function SnapListToArray() {
   local COUNT=0
   for SNAPLIST in `aws ec2 describe-snapshots --output=text --filter \
      "Name=description,Values=*_${THISINSTID}-bkup*" --query \
      "Snapshots[].{F1:SnapshotId,F3:Description,F2:StartTime}" | \
      tr '\t' ';'`
   do
      SNAPARRAY[${COUNT}]="${SNAPLIST}"
      local COUNT=$((${COUNT} +1))
   done
}

SnapListToArray

echo ${SNAPARRAY[@]}
